@HostAddress = http://localhost:5230

POST {{HostAddress}}/get-users/
Content-Type: application/json

{}

###

POST {{HostAddress}}/create-user/
Content-Type: application/json

{
  "name": "I am another guy"
}