using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Framework.Generators;

[Generator(LanguageNames.CSharp)]
public class ApiGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c &&
                                            c.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m is not null);

        var collectedHandlers = handlerDeclarations.Collect();

        context.RegisterSourceOutput(collectedHandlers,
            static (spc, handlers) => Execute(spc, handlers));
    }

    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

        if (classSymbol == null) return null;

        var hasApiDefinitionAttr = classSymbol.GetAttributes()
            .Any(ad => ad.AttributeClass?.Name == "ApiDefinition" ||
                       ad.AttributeClass?.Name == "ApiDefinitionAttribute");

        return hasApiDefinitionAttr ? classSymbol : null;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> handlers)
    {
        CreateExtensionMethod(context, handlers);
    }

    private static void CreateExtensionMethod(SourceProductionContext context,
        ImmutableArray<INamedTypeSymbol?> handlers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine();
        sb.AppendLine("namespace ApiGeneratR.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class ApiExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static void AddApiEndpoints(this WebApplication app)");
        sb.AppendLine("    {");

        if (!handlers.IsDefaultOrEmpty)
        {
            foreach (var handler in handlers)
            {
                if (handler == null) continue;

                var attribute = handler.GetAttributes()
                    .First(a => a.AttributeClass?.Name == "ApiDefinition");

                var route = attribute.ConstructorArguments[0].Value?.ToString();
                var handlerType = handler.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sb.AppendLine(
                    $"        app.MapPost(\"{route}\", async ({handlerType} request, global::Framework.Contract.Mediator.IMediator mediator) =>");
                sb.AppendLine("        {");
                sb.AppendLine($"            return await mediator.HandleAsync(request);");
                sb.AppendLine("        });");
                sb.AppendLine();
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ApiExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}