using System.Collections.Immutable;
using System.Text;
using Framework.Generators.Builder;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Framework.Generators;

[Generator(LanguageNames.CSharp)]
public class MediatorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m is not null);

        var collectedHandlers = handlerDeclarations.Collect();

        context.RegisterSourceOutput(collectedHandlers,
            static (spc, handlers) => Execute(spc, handlers));
    }

    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext ctx)
    {
        var classSymbol = ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol;

        return classSymbol != null && classSymbol.AllInterfaces.Any(i => i.Name == "IRequestHandler")
            ? classSymbol
            : null;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> handlers)
    {
        CreateSourceMediator(context, handlers);
        CreateExtensionMethod(context, handlers);
    }

    private static void CreateExtensionMethod(SourceProductionContext context,
        ImmutableArray<INamedTypeSymbol?> handlers)
    {
        var scb = new SourceCodeBuilder();

        scb.SetUsings([
            "System", "System.Collections.Generic", "System.Threading", "System.Threading.Tasks",
            "Microsoft.Extensions.DependencyInjection"
        ]);
        scb.SetNamespace("Mediator.Generated");
        scb.StartScope("public static class MediatorExtensions");
        scb.StartScope("extension(IServiceCollection services)");
        scb.StartScope("public void AddSingletonMediatorServices()");
        scb.AddLine("services.AddSingleton<global::Framework.Contract.Mediator.IMediator, SourceMediator>();");
        if (!handlers.IsDefaultOrEmpty)
        {
            foreach (var handler in handlers)
            {
                if (handler == null) continue;

                var interfaceSymbol = handler.AllInterfaces.FirstOrDefault(i =>
                    i.Name == "IRequestHandler" &&
                    i.ContainingNamespace.ToDisplayString().Contains("Framework.Contract"));

                if (interfaceSymbol == null || interfaceSymbol.TypeArguments.Length != 2) continue;

                var requestType = interfaceSymbol.TypeArguments[0]
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var responseType = interfaceSymbol.TypeArguments[1]
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var handlerType = handler.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                scb.AddLine(
                    $"services.AddSingleton<global::Framework.Contract.Mediator.IRequestHandler<{requestType}, {responseType}>, {handlerType}>();");
            }
        }

        scb.EndScope();
        scb.EndScope();
        scb.EndScope();

        context.AddSource("MediatorExtensions.g.cs", SourceText.From(scb.ToString(), Encoding.UTF8));
    }

    private static void CreateMediator(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> handlers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Mediator.Generated;");
        sb.AppendLine();
        sb.AppendLine("public class SourceMediator : global::Framework.Contract.Mediator.IMediator");
        sb.AppendLine("{");
        sb.AppendLine(
            "    private readonly Dictionary<Type, Func<object, CancellationToken, Task<object>>> _handlers = new();");
        sb.AppendLine("    private readonly IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine($"    public SourceMediator(IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("        _serviceProvider = serviceProvider;");
        sb.AppendLine("        RegisterHandlers();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private void RegisterHandlers()");
        sb.AppendLine("    {");

        if (!handlers.IsDefaultOrEmpty)
        {
            foreach (var handler in handlers)
            {
                if (handler == null) continue;

                var interfaceSymbol = handler.AllInterfaces.FirstOrDefault(i =>
                    i.Name == "IRequestHandler" &&
                    i.ContainingNamespace.ToDisplayString().Contains("Framework.Contract"));

                if (interfaceSymbol == null || interfaceSymbol.TypeArguments.Length != 2) continue;

                var requestType = interfaceSymbol.TypeArguments[0]
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var handlerType = handler.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sb.AppendLine($"        _handlers.Add(typeof({requestType}), async (req, ct) =>");
                sb.AppendLine("        {");
                sb.AppendLine(
                    $"            var handler = (_serviceProvider.GetService(typeof({handlerType})) as {handlerType})");
                sb.AppendLine(
                    $"                          ?? ActivatorUtilities.CreateInstance<{handlerType}>(_serviceProvider);");
                sb.AppendLine($"            var result = await handler.HandleAsync(({requestType})req);");
                sb.AppendLine("            return (object)result;");
                sb.AppendLine("        });");

                if (!SymbolEqualityComparer.Default.Equals(handler, handlers.Last()))
                {
                    sb.AppendLine();
                }
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine(
            "    public async Task<TResponse> HandleAsync<TResponse>(global::Framework.Contract.Mediator.IRequest<TResponse> request, CancellationToken ct = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (request == null) throw new ArgumentNullException(\"request is null\");");
        sb.AppendLine();
        sb.AppendLine("        if (!_handlers.TryGetValue(request.GetType(), out var handlerWrapper))");
        sb.AppendLine("            throw new Exception($\"Handler for type {request.GetType()} not found\");");
        sb.AppendLine();
        sb.AppendLine("        return (TResponse)await handlerWrapper(request, ct);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("SourceMediator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void CreateSourceMediator(SourceProductionContext context,
        ImmutableArray<INamedTypeSymbol?> handlers)
    {
        var scb = new SourceCodeBuilder();

        scb.SetUsings([
            "System", "System.Collections.Generic", "System.Threading",
            "System.Threading.Tasks", "Microsoft.Extensions.DependencyInjection"
        ]);
        scb.SetNamespace("Mediator.Generated");

        scb.StartScope("public class SourceMediator : global::Framework.Contract.Mediator.IMediator");

        scb.AddLine(
            "private readonly Dictionary<Type, Func<object, CancellationToken, Task<object>>> _handlers = new();");
        scb.AddLine("private readonly IServiceProvider _serviceProvider;");
        scb.AddLine("");

        scb.StartScope("public SourceMediator(IServiceProvider serviceProvider)");
        scb.AddLine("_serviceProvider = serviceProvider;");
        scb.AddLine("RegisterHandlers();");
        scb.EndScope();
        scb.AddLine("");

        scb.StartScope("private void RegisterHandlers()");

        if (!handlers.IsDefaultOrEmpty)
        {
            foreach (var handler in handlers)
            {
                if (handler == null) continue;

                var interfaceSymbol = handler.AllInterfaces.FirstOrDefault(i =>
                    i.Name == "IRequestHandler" &&
                    i.ContainingNamespace.ToDisplayString().Contains("Framework.Contract"));

                if (interfaceSymbol == null || interfaceSymbol.TypeArguments.Length != 2) continue;

                var requestType = interfaceSymbol.TypeArguments[0]
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var handlerType = handler.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                scb.StartScope($"_handlers.Add(typeof({requestType}), async (req, ct) =>");
                scb.AddLine($"var handler = (_serviceProvider.GetService(typeof({handlerType})) as {handlerType})");
                scb.AddLine($"              ?? ActivatorUtilities.CreateInstance<{handlerType}>(_serviceProvider);");
                scb.AddLine($"var result = await handler.HandleAsync(({requestType})req);");
                scb.AddLine("return (object)result;");
                scb.EndScope(");");

                if (!SymbolEqualityComparer.Default.Equals(handler, handlers.Last()))
                {
                    scb.AddLine("");
                }
            }
        }

        scb.EndScope();
        scb.AddLine("");

        scb.StartScope(
            "public async Task<TResponse> HandleAsync<TResponse>(global::Framework.Contract.Mediator.IRequest<TResponse> request, CancellationToken ct = default)");
        scb.AddLine("if (request == null) throw new ArgumentNullException(\"request is null\");");
        scb.AddLine("");
        scb.AddLine("if (!_handlers.TryGetValue(request.GetType(), out var handlerWrapper))");
        scb.AddLine("    throw new Exception($\"Handler for type {request.GetType()} not found\");");
        scb.AddLine("");
        scb.AddLine("return (TResponse)await handlerWrapper(request, ct);");
        scb.EndScope();

        scb.EndScope();

        context.AddSource("SourceMediator.g.cs", SourceText.From(scb.ToString(), Encoding.UTF8));
    }
}