using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Framework.Generators;

[Generator(LanguageNames.CSharp)]
public class RepositoryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c &&
                                            c.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m is not null);

        var collectedHandlers = handlerDeclarations.Collect();

        context.RegisterSourceOutput(collectedHandlers,
            static (spc, handlers) => Execute(spc, handlers));
    }

    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

        if (classSymbol == null) return null;

        var hasDomainEntityAttr = classSymbol.GetAttributes()
            .Any(ad => ad.AttributeClass?.Name == "DomainEntity" ||
                       ad.AttributeClass?.Name == "DomainEntityAttribute");

        return hasDomainEntityAttr ? classSymbol : null;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> handlers)
    {
        CreateRepositories(context, handlers);
        CreateExtensionMethod(context, handlers);
    }

    private static void CreateExtensionMethod(SourceProductionContext context,
        ImmutableArray<INamedTypeSymbol?> handlers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Repository.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class RepositoryExtensions");
        sb.AppendLine("{");
        sb.AppendLine("     extension(IServiceCollection services)");
        sb.AppendLine("     {");
        sb.AppendLine("         public void AddSingletonRepositoryServices()");
        sb.AppendLine("         {");
        if (!handlers.IsDefaultOrEmpty)
        {
            foreach (var handler in handlers)
            {
                if (handler == null) continue;

                var interfaceSymbol = handler.AllInterfaces.FirstOrDefault(i =>
                    i.Name == "IRepository" &&
                    i.ContainingNamespace.ToDisplayString().Contains("Framework.Contract"));

                if (interfaceSymbol == null || interfaceSymbol.TypeArguments.Length != 1) continue;

                var entityType = interfaceSymbol.TypeArguments[0]
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var repositoryType = handler.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sb.AppendLine(
                    $"             services.AddSingleton<global::Framework.Contract.Repository.IRepository<{entityType}>, {repositoryType}>();");
            }
        }

        sb.AppendLine("         }");
        sb.AppendLine("     }");
        sb.AppendLine("}");

        context.AddSource("RepositoryExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void CreateRepositories(SourceProductionContext context,
        ImmutableArray<INamedTypeSymbol?> entities)
    {
        if (entities.IsDefaultOrEmpty) return;

        foreach (var entity in entities)
        {
            if (entity == null) continue;

            var attribute = entity.GetAttributes()
                .First(a => a.AttributeClass?.Name == "DomainEntity");

            var route = attribute.ConstructorArguments[0].Value?.ToString();
            var entityType = entity.Name;
            var fullyQualifiedEntity = entity.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using Framework.Contract.Repository;");
            sb.AppendLine();
            sb.AppendLine("namespace ApiGeneratR.Generated;");
            sb.AppendLine();
            sb.AppendLine(
                $"public class {entityType}MockRepository : global::Framework.Contract.Repository.IRepository<{fullyQualifiedEntity}>");
            sb.AppendLine("{");
            sb.AppendLine($"    private readonly List<{fullyQualifiedEntity}> {entityType}List = [];");
            sb.AppendLine();
            sb.AppendLine($"    public Task AddAsync({fullyQualifiedEntity} entity)");
            sb.AppendLine("    {");
            sb.AppendLine($"        {entityType}List.Add(entity);");
            sb.AppendLine("        return Task.CompletedTask;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    public Task<{fullyQualifiedEntity}> GetByIdAsync(Guid id)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return Task.FromResult({entityType}List.FirstOrDefault(e => e.Id == id));");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine(
                $"    public Task<List<{fullyQualifiedEntity}>> GetAllAsync() => Task.FromResult({entityType}List);");
            sb.AppendLine();
            sb.AppendLine($"    public Task UpdateAsync({fullyQualifiedEntity} entity)");
            sb.AppendLine("    {");
            sb.AppendLine($"        var index = {entityType}List.FindIndex(e => e.Id == entity.Id);");
            sb.AppendLine($"        if(index != -1) {entityType}List[index] = entity;");
            sb.AppendLine("        return Task.CompletedTask;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public Task DeleteAsync(Guid id)");
            sb.AppendLine("    {");
            sb.AppendLine($"        var {entityType}Item = {entityType}List.FirstOrDefault(e => e.Id == id);");
            sb.AppendLine($"        if({entityType}Item == null) return Task.CompletedTask;");
            sb.AppendLine($"        {entityType}List.Remove({entityType}Item);");
            sb.AppendLine("        return Task.CompletedTask;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine(
                $"    public Task<bool> ExistsAsync(Guid id) => Task.FromResult({entityType}List.Any(e => e.Id == id));");
            sb.AppendLine("}");

            context.AddSource($"{entityType}MockRepository.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}