using System.Text;

namespace Framework.Generators.Builder;

public class SourceCodeBuilder
{
    private readonly StringBuilder _sb = new();
    private readonly HashSet<string> _usings = new();
    private string _namespace = string.Empty;
    private int _indentLevel = 0;
    private const int IndentSize = 4;

    public void SetUsings(IEnumerable<string> usings)
    {
        foreach (var u in usings) _usings.Add(u);
    }
    
    public void AddUsing(string ns) => _usings.Add(ns);

    public void SetNamespace(string ns) => _namespace = ns;

    public void StartScope(string line)
    {
        AddLine(line);
        AddLine("{");
        _indentLevel++;
    }

    public void EndScope(string customEnd = "")
    {
        _indentLevel = Math.Max(0, _indentLevel - 1);
        AddLine("}" + customEnd);
    }

    public void AddIndentedLine(string line)
    {
        _sb.Append(' ', (_indentLevel + 1) * IndentSize);
        _sb.AppendLine(line);
    }

    public void AddLine(string line = "")
    {
        if (string.IsNullOrWhiteSpace(line))
        {
            _sb.AppendLine();
            return;
        }

        _sb.Append(' ', _indentLevel * IndentSize);
        _sb.AppendLine(line);
    }

    public override string ToString()
    {
        var result = new StringBuilder();
        result.AppendLine("// <auto-generated />");

        foreach (var u in _usings.OrderBy(x => x))
            result.AppendLine($"using {u};");

        if (!string.IsNullOrEmpty(_namespace))
        {
            result.AppendLine();
            result.AppendLine($"namespace {_namespace};");
            result.AppendLine();
        }

        result.Append(_sb);
        return result.ToString();
    }
}